### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by evanlinwood** [thomast1906/deploy-first-containerapp-terraform#15]
Hi - it appears that the source code for the sample app is no longer in the repo, I'm wondering can you please provide a reference to it? Thnks

**Comment by thomast1906** [comment]
Sorry, missed this notification - will resolve shortly

**Comment by thomast1906** [comment]
sourcecode is here? https://github.com/thomast1906/deploy-first-containerapp-terraform/tree/main/aspnet-core-dotnet-core

**Comment by thomast1906** [comment]
Will close this issue now
